# Generated by Django 5.2.11 on 2026-02-19 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('events', '0001_initial'),
        ('stalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='owner_stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ledger_accounts', to='stalls.stall'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ledger_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='staffcreditgrant',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_grants_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffcreditgrant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_grants', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='staffcreditgrant',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_credit_grants_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuprecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_records', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='topuprecord',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_topups_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletbalancecache',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balances', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='walletbalancecache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['event', 'account_type'], name='accounting__event_i_513128_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['event', 'owner_user'], name='accounting__event_i_d96b8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='uniq_ledger_account_code_by_event'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['event', 'tx_type', 'created_at'], name='accounting__event_i_93219f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['event', 'created_at'], name='accounting__event_i_e33e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'id'], name='accounting__account_053455_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction', 'id'], name='accounting__transac_ef3acd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_mxn_signed', 0), _negated=True), name='check_ledger_entry_nonzero_amount'),
        ),
        migrations.AddIndex(
            model_name='staffcreditgrant',
            index=models.Index(fields=['event', 'created_at'], name='accounting__event_i_061a33_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcreditgrant',
            index=models.Index(fields=['client_user', 'created_at'], name='accounting__client__acc54c_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffcreditgrant',
            constraint=models.CheckConstraint(condition=models.Q(('amount_ucoin__gt', 0)), name='check_staff_credit_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='topuprecord',
            index=models.Index(fields=['event', 'user', 'created_at'], name='accounting__event_i_0f8aba_idx'),
        ),
        migrations.AddIndex(
            model_name='topuprecord',
            index=models.Index(fields=['provider', 'provider_ref'], name='accounting__provide_fe0adb_idx'),
        ),
        migrations.AddConstraint(
            model_name='topuprecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_ucoin__gt', 0)), name='check_topup_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='topuprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('event', 'source_reference'), name='uniq_nonempty_topup_source_reference_by_event'),
        ),
        migrations.AddIndex(
            model_name='walletbalancecache',
            index=models.Index(fields=['event', 'updated_at'], name='accounting__event_i_bbe58c_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletbalancecache',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uniq_wallet_balance_cache_event_user'),
        ),
    ]
