# Generated by Django 5.2.11 on 2026-02-19 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('photo_variant', models.CharField(default='taco', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_zones', to='events.eventcampaign')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('x', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('y', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('blocked', 'Bloqueado')], default='available', max_length=16)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_spots', to='events.eventcampaign')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='stalls.mapzone')),
            ],
            options={
                'ordering': ['zone__sort_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierto'), ('paused', 'Pausado'), ('closed', 'Cerrado')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='events.eventcampaign')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_stall_assignments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stall_assignments', to='events.eventcampaign')),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stall_assignment', to='stalls.mapspot')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stalls.stall')),
                ('vendor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stall_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StallProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('price_ucoin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_mode', models.CharField(choices=[('finite', 'Finito'), ('unlimited', 'Ilimitado')], default='finite', max_length=16)),
                ('stock_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sold_out_manual', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stall_products', to='stalls.catalogproduct')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stall_products', to='events.eventcampaign')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stalls.stall')),
            ],
            options={
                'ordering': ['stall__name', 'display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('set', 'Ajuste inicial'), ('increase', 'Incremento'), ('decrease', 'Decremento'), ('adjust', 'Ajuste manual'), ('sale', 'Venta')], max_length=16)),
                ('quantity_delta', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='events.eventcampaign')),
                ('stall_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stalls.stallproduct')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mapzone',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='uniq_zone_name_by_event'),
        ),
        migrations.AddIndex(
            model_name='mapspot',
            index=models.Index(fields=['event', 'status'], name='stalls_maps_event_i_c2af37_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapspot',
            constraint=models.UniqueConstraint(fields=('event', 'label'), name='uniq_spot_label_by_event'),
        ),
        migrations.AddIndex(
            model_name='stall',
            index=models.Index(fields=['event', 'status'], name='stalls_stal_event_i_6bdce4_idx'),
        ),
        migrations.AddConstraint(
            model_name='stall',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='uniq_stall_code_by_event'),
        ),
        migrations.AddConstraint(
            model_name='stallassignment',
            constraint=models.UniqueConstraint(fields=('event', 'vendor_user'), name='uniq_vendor_per_event'),
        ),
        migrations.AddConstraint(
            model_name='stallassignment',
            constraint=models.UniqueConstraint(fields=('event', 'spot'), name='uniq_spot_assignment_per_event'),
        ),
        migrations.AddConstraint(
            model_name='stallassignment',
            constraint=models.UniqueConstraint(fields=('event', 'stall'), name='uniq_stall_assignment_per_event'),
        ),
        migrations.AddIndex(
            model_name='stallproduct',
            index=models.Index(fields=['event', 'stall', 'is_active'], name='stalls_stal_event_i_35dff1_idx'),
        ),
        migrations.AddIndex(
            model_name='stallproduct',
            index=models.Index(fields=['event', 'is_active'], name='stalls_stal_event_i_aeeaef_idx'),
        ),
        migrations.AddConstraint(
            model_name='stallproduct',
            constraint=models.UniqueConstraint(fields=('event', 'stall', 'catalog_product'), name='uniq_stall_catalog_product_by_event'),
        ),
        migrations.AddConstraint(
            model_name='stallproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price_ucoin__gte', 0)), name='check_stall_product_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stallproduct',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stock_mode', 'unlimited'), ('stock_qty__isnull', True)), models.Q(('stock_mode', 'finite'), ('stock_qty__gte', 0), ('stock_qty__isnull', False)), _connector='OR'), name='check_stall_product_stock_consistency'),
        ),
        migrations.AddConstraint(
            model_name='stallproduct',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__isnull', True), ('low_stock_threshold__gte', 0), _connector='OR'), name='check_low_stock_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['event', 'created_at'], name='stalls_stoc_event_i_0dc618_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stall_product', 'created_at'], name='stalls_stoc_stall_p_eae70c_idx'),
        ),
    ]
