# Generated by Django 5.2.11 on 2026-02-19 06:22

import django.db.models.deletion
from django.db import migrations, models


def seed_taxonomy_and_backfill(apps, schema_editor):
    ProductCategory = apps.get_model("stalls", "ProductCategory")
    ProductSubcategory = apps.get_model("stalls", "ProductSubcategory")
    StallProduct = apps.get_model("stalls", "StallProduct")
    CatalogProduct = apps.get_model("stalls", "CatalogProduct")

    category_specs = [
        (
            "alimento",
            "Alimento",
            1,
            [
                ("snack", "Snack", 1, "combo", "core/img/products/default-alimento.svg"),
                ("comida-corrida", "Comida corrida", 2, "taco", "core/img/products/default-alimento.svg"),
                ("postre", "Postre", 3, "postre", "core/img/products/default-alimento.svg"),
            ],
        ),
        (
            "bebida",
            "Bebida",
            2,
            [
                ("fria", "Fria", 1, "agua", "core/img/products/default-bebida.svg"),
                ("caliente", "Caliente", 2, "cafe", "core/img/products/default-bebida.svg"),
                ("natural", "Natural", 3, "agua", "core/img/products/default-bebida.svg"),
            ],
        ),
        (
            "servicio",
            "Servicio",
            3,
            [
                ("recarga", "Recarga", 1, "combo", "core/img/products/default-servicio.svg"),
                ("paquete", "Paquete", 2, "combo", "core/img/products/default-servicio.svg"),
                ("otro-servicio", "Otro", 3, "combo", "core/img/products/default-servicio.svg"),
            ],
        ),
    ]

    for category_slug, category_name, category_sort, subcategories in category_specs:
        category, _ = ProductCategory.objects.get_or_create(
            slug=category_slug,
            defaults={"name": category_name, "sort_order": category_sort, "is_active": True},
        )
        for sub_slug, sub_name, sub_sort, variant, image in subcategories:
            subcategory, _ = ProductSubcategory.objects.get_or_create(
                slug=sub_slug,
                defaults={
                    "category": category,
                    "name": sub_name,
                    "sort_order": sub_sort,
                    "is_active": True,
                    "default_photo_variant": variant,
                    "default_image": image,
                },
            )

    default_category = ProductCategory.objects.get(slug="alimento")
    default_subcategory = ProductSubcategory.objects.get(slug="snack")

    for product in StallProduct.objects.all():
        fields_to_update = []
        if not product.category_id:
            product.category = default_category
            fields_to_update.append("category")
        if not product.subcategory_id:
            product.subcategory = default_subcategory
            fields_to_update.append("subcategory")

        if product.item_nature == "no_inventoriable":
            product.stock_mode = "unlimited"
            product.stock_qty = None
            product.stock_base_qty = None
            product.low_stock_threshold = None
            fields_to_update.extend(["stock_mode", "stock_qty", "stock_base_qty", "low_stock_threshold"])
        else:
            if product.stock_mode != "finite":
                product.stock_mode = "finite"
                fields_to_update.append("stock_mode")
            if product.stock_qty is None:
                product.stock_qty = 0
                fields_to_update.append("stock_qty")
            if product.stock_base_qty is None or product.stock_qty > product.stock_base_qty:
                product.stock_base_qty = product.stock_qty
                fields_to_update.append("stock_base_qty")
            if product.stock_base_qty and product.stock_base_qty > 0:
                threshold = max(1, (product.stock_base_qty * 15 + 99) // 100)
            else:
                threshold = None
            if product.low_stock_threshold != threshold:
                product.low_stock_threshold = threshold
                fields_to_update.append("low_stock_threshold")

        if fields_to_update:
            product.save(update_fields=list(dict.fromkeys(fields_to_update)))

    for product in StallProduct.objects.select_related("catalog_product", "subcategory"):
        subcategory = product.subcategory or default_subcategory
        if product.catalog_product and product.catalog_product.photo_variant != subcategory.default_photo_variant:
            CatalogProduct.objects.filter(pk=product.catalog_product_id).update(
                photo_variant=subcategory.default_photo_variant
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_defaults'),
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='cost_ucoin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='item_nature',
            field=models.CharField(choices=[('inventoriable', 'Inventariable'), ('no_inventoriable', 'No inventariable')], default='inventoriable', max_length=24),
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='stock_base_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stall_products', to='stalls.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('default_photo_variant', models.CharField(default='combo', max_length=32)),
                ('default_image', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='stalls.productcategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stallproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stall_products', to='stalls.productsubcategory'),
        ),
        migrations.AddIndex(
            model_name='stallproduct',
            index=models.Index(fields=['event', 'category', 'subcategory'], name='stalls_stal_event_i_115dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='stallproduct',
            index=models.Index(fields=['event', 'item_nature', 'is_active'], name='stalls_stal_event_i_a9087b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_subcategory_name_by_category'),
        ),
        migrations.RunPython(seed_taxonomy_and_backfill, noop_reverse),
    ]
