# Generated by Django 5.2.11 on 2026-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_productcategory_stallproduct_cost_ucoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='stalls/'),
        ),
    ]
