# Generated by Django 5.2.11 on 2026-08-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0005_backfill_stall_assignment_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stalllocationassignment',
            new_name='stalls_stal_event_i_a3dd0d_idx',
            old_name='stalls_sla_event_stall_idx',
        ),
        migrations.RenameIndex(
            model_name='stalllocationassignment',
            new_name='stalls_stal_event_i_76ab74_idx',
            old_name='stalls_sla_event_spot_idx',
        ),
        migrations.RenameIndex(
            model_name='stallvendormembership',
            new_name='stalls_stal_event_i_afad45_idx',
            old_name='stalls_svm_event_stall_idx',
        ),
        migrations.RenameIndex(
            model_name='stallvendormembership',
            new_name='stalls_stal_event_i_3d2a50_idx',
            old_name='stalls_svm_event_vendor_idx',
        ),
    ]
