# Generated by Django 5.2.11 on 2026-08-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0006_convert_to_event_scoped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StallAssignment',
        ),
    ]
