# Generated by Django 5.2.11 on 2026-02-19 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='events_even_status_57f4f1_idx'), models.Index(fields=['starts_at', 'ends_at'], name='events_even_starts__b8e9d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('comunidad', 'Comunidad'), ('invitado', 'Invitado')], default='comunidad', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('invited_by_email', models.EmailField(blank=True, max_length=254)),
                ('invited_by_matricula', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.eventcampaign')),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'profile_type'], name='events_even_event_i_42d7cc_idx'), models.Index(fields=['user', 'created_at'], name='events_even_user_id_fa0934_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='uniq_event_membership_user')],
            },
        ),
        migrations.CreateModel(
            name='EventUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='events.eventcampaign')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'group', 'user'], name='events_even_event_i_c4ae51_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'group'), name='uniq_event_user_group')],
            },
        ),
    ]
