# Generated by Django 5.2.11 on 2026-02-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventusergroup',
            options={'permissions': [('access_cliente_portal', 'Puede acceder al portal cliente'), ('checkout_cart', 'Puede ejecutar checkout de carrito'), ('access_vendedor_portal', 'Puede acceder al portal vendedor'), ('manage_vendor_products', 'Puede crear y editar productos de vendedor'), ('soft_delete_vendor_products', 'Puede desactivar productos de vendedor'), ('manage_vendor_stall_image', 'Puede administrar imagen de su tienda'), ('verify_order_qr', 'Puede verificar QR de orden'), ('access_staff_panel', 'Puede acceder al panel staff'), ('manage_event_profiles', 'Puede gestionar perfiles por evento'), ('assign_vendor_stall', 'Puede asignar vendedor a puesto y espacio'), ('grant_ucoins', 'Puede otorgar ucoins a clientes')]},
        ),
    ]
