# Generated by Django 5.2.11 on 2026-02-19 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('events', '0001_initial'),
        ('stalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_v2', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stall_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_v2', to='stalls.stallproduct'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdeliverylog',
            name='performed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='buyer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='events.eventcampaign'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='stalls.stall'),
        ),
        migrations.AddField(
            model_name='orderqrtoken',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='orderdeliverylog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='stall_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='stalls.stallproduct'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['event', 'user', 'updated_at'], name='commerce_ca_event_i_7c3b7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'stall_product'), name='uniq_cart_item_event_user_stall_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_cart_item_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['event', 'buyer_user', 'created_at'], name='commerce_sa_event_i_249ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['event', 'stall', 'created_at'], name='commerce_sa_event_i_dfb77d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['event', 'status', 'created_at'], name='commerce_sa_event_i_f5887a_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('event', 'order_number'), name='uniq_order_number_by_event'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('event', 'source_reference'), name='uniq_nonempty_source_reference_by_event'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_ucoin__gte', 0)), name='check_sales_order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_ucoin__gte', 0)), name='check_sales_order_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='orderqrtoken',
            index=models.Index(fields=['order', 'is_active', 'expires_at'], name='commerce_or_order_i_9a6a25_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdeliverylog',
            index=models.Index(fields=['order', 'created_at'], name='commerce_or_order_i_7a531f_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_sales_order_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 0)), name='check_sales_order_item_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_snapshot__gte', 0)), name='check_sales_order_item_line_total_nonnegative'),
        ),
    ]
